CREATE TABLE "registrations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"title" text,
	"organization" text,
	"mobile_phone" text,
	"address_line_1" text,
	"address_line_2" text,
	"city" text,
	"state" text,
	"zip" text,
	"country" text,
	"emergency_contact_name" text,
	"emergency_contact_relation" text,
	"emergency_contact_email" text,
	"emergency_contact_phone" text,
	"assistant_name" text,
	"assistant_title" text,
	"assistant_email" text,
	"assistant_phone" text,
	"guest_name" text,
	"guest_relation" text,
	"guest_email" text,
	"dietary_restrictions" text,
	"jacket_size" text,
	"accommodations" text,
	"dinner_attendance" text,
	"activities" text,
	"guest_dietary_restrictions" text,
	"guest_jacket_size" text,
	"guest_accommodations" text,
	"guest_dinner_attendance" text,
	"guest_activities" text,
	CONSTRAINT "registrations_email_unique" UNIQUE("email")
);
